# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'rspec' # meta gem, has multiple gems inside
gem 'pry'
gem 'byebug'
